name = "lounge-idle-tg-sync"
main = "src/index.js"
compatibility_date = "2024-11-01"
workers_dev = true

[[kv_namespaces]]
binding = "SAVES"
id = "69487405caa445ef977c2c6a8ecde2f0"
preview_id = "69487405caa445ef977c2c6a8ecde2f0"
